### ISSUE TITLE
Can't find rpcs3 in RetroPie Setup?

### ISSUE THREAD

**Issue by floopda** [raelgc/retropie_rpcs3#2]
I've been tinkering with this for days now, but I checked ~/RetroPie-Setup/platforms.cfg for PS3 , and it wasn't there. So, I made a platforms.cfg file in /opt/retropie/configs/all. Then I ran wget https://raw.githubusercontent.com/raelgc/retropie_rpcs3/master/rpcs3.sh -O ~/RetroPie-Setup/scriptmodules/emulators/rpcs3.sh, looked for rpcs3 in RetroPie Setup, and it wasn't there. After retrying many times with different variations of the command, I gave up on that and MANUALLY TYPED the code into ~/RetroPie-Setup/scriptmodules/emulators. After checking the code and correcting my typos, I went back to RetroPie Setup and still didn't see it. Please help!

**Comment by raelgc** [comment]
Hi @floopda and sorry about your frustration with this.

I had no idea why the `platform.cfg` is not present at your install.

By the way, are you running this on a PC (not a raspberry), right?

**Comment by floopda** [comment]
Nope, I'm on a raspberry 3 (1up piboy).

**Comment by floopda** [comment]
I think I'm closer. I figured out how to use the wget command and from the little I know about this, all the files are in the right places for rpcs3 to show up in the exp list. altough it isn't );

**Comment by raelgc** [comment]
@floopda The below script line prevents the script to run on an `arm` platform:

> rp_module_flags="!arm"

But even if you remove it, the `appImage` file built by rpcs3 team is made for Linux in the x86 platform (PC).

Even if you try to compile it manually, I don't think a raspberry has the power yet to run rpcs3. Probably in the near future.
