### ISSUE TITLE
Missing install option

### ISSUE THREAD

**Issue by mpeirone** [raelgc/retropie_rpcs3#3]
Hi, the installation is no longer allowed after the id has been changed.
I noticed that the functions don´t match with the new id. You need to rename those functions like this:

- install_bin_rpcs3 --> configure_rpcs3-appImage
- configure_rpcs3 --> configure_rpcs3-appImage

Thanks for your great work

Matteo

**Comment by raelgc** [comment]
Oh, nice catch, @mpeirone!
